### ISSUE TITLE
Train Problem

### ISSUE THREAD

**Issue by scw318** [IanYangChina/DRL_Implementation#2]
Thank you for your reinforcement learning algorithm and environment implementation.
However,when I  used the example about KukaPushPHER , the avg return was from -40 to -50, and the success rate from 0.0 to 0.2.
I did not  modify any parameters and I did’t know why this happened.Can you give me some advice about it?Thank you a lot.

**Comment by IanYangChina** [comment]
Hi, thanks for the report. The PMG environment and the HER algorithm are sometimes sensitive to random seeds. You can try to run with more different random seeds and see how it goes. Check out this [repo](https://github.com/IanYangChina/taros2021codes) as well.

**Comment by IanYangChina** [comment]
> Thank you for your reinforcement learning algorithm and environment implementation.
> However,when I used the example about KukaPushPHER , the avg return was from -40 to -50, and the success rate from 0.0 to 0.2.
> I did not modify any parameters and I did’t know why this happened.Can you give me some advice about it?Thank you a lot.

Hi, thanks for the report. The PMG environment and the HER algorithm are sometimes sensitive to random seeds. You can try to run with more different random seeds and see how it goes. Check out this [repo](https://github.com/IanYangChina/taros2021codes) as well.

**Comment by scw318** [comment]
Thank you very much, I will try it.
