### ISSUE TITLE
Reproducing pick and place result

### ISSUE THREAD

**Issue by seann999** [IanYangChina/DRL_Implementation#3]
Hi, I was trying to reproduce this result from the paper
![image](https://user-images.githubusercontent.com/6847529/135593283-ca76d86c-1cb6-4be1-a0bb-64b54885c062.png)
So I replaced the task argument in
https://github.com/IanYangChina/DRL_Implementation/blob/master/drl_implementation/examples/KukaPushPHER.py
to pick_and_place, but this is the result I got for one seed (test success rate):
![image](https://user-images.githubusercontent.com/6847529/135593561-3029dcfc-d2c2-4087-8d56-54b6c889febd.png)
If I am reading the y-axis in the paper correctly, I was expecting almost perfect success rate by epoch 30, but my result seems to settle at 60%.
Is there something that is different that I need to modify?

**Comment by seann999** [comment]
Here is a video during testing. The agent learned to push quite well but seems to have had a hard time learning mid-air goals.
![Peek 2021-10-01 18-03](https://user-images.githubusercontent.com/6847529/135594697-d780c714-d482-4dc2-b70f-763a7d6e0ac5.gif)

**Comment by IanYangChina** [comment]
Hi, thanks for the report.
I have noticed this problem with other tasks as well.
It comes from the environment side, not the algorithm. 
I'm working on it at the moment, let's hope that I can get it done ASAP :)
You are very welcome to take a look into the environment package as well, if you'd like to. 
Thanks!

**Comment by IanYangChina** [comment]
> Hi, I was trying to reproduce this result from the paper ![image](https://user-images.githubusercontent.com/6847529/135593283-ca76d86c-1cb6-4be1-a0bb-64b54885c062.png) So I replaced the task argument in https://github.com/IanYangChina/DRL_Implementation/blob/master/drl_implementation/examples/KukaPushPHER.py to pick_and_place, but this is the result I got for one seed (test success rate): ![image](https://user-images.githubusercontent.com/6847529/135593561-3029dcfc-d2c2-4087-8d56-54b6c889febd.png) If I am reading the y-axis in the paper correctly, I was expecting almost perfect success rate by epoch 30, but my result seems to settle at 60%. Is there something that is different that I need to modify?

Hi I have fixed the issue.
It turns out that the problem was with the joint forces I setup to control the kuka arm.
As expected, it's not with the algorithms.
Please install the lastest version of the [environment package](https://github.com/IanYangChina/pybullet_multigoal_gym/tree/master) using:
```
git clone https://github.com/IanYangChina/pybullet_multigoal_gym.git
cd pybullet_multigoal_gym
conda activate YourEnv (optional)
python -m pip install .
```

Then return to the example script and have another try.
Thanks

**Comment by IanYangChina** [comment]
Issue closed as solved.
